export const blogPosts = [
  {
    id: "ai-security-trends-2025",
    title: "Top AI Security Trends to Watch in 2025",
    excerpt:
      "As AI systems become more prevalent, new security challenges emerge. Here's what organizations need to prepare for in the coming year.",
    coverImage: "/blog/ai-security.jpg",
    category: "Trends",
    tags: ["AI Security", "Machine Learning", "Threat Detection"],
    author: {
      name: "John Doe",
      avatar: "/avatars/john-doe.jpg",
      role: "Chief Research Officer",
    },
    publishedAt: "2025-04-01",
    readTime: "8 min read",
    likes: 124,
    comments: 32,
  },
  {
    id: "prompt-injection-defenses",
    title: "Defending Against Prompt Injection Attacks",
    excerpt:
      "Prompt injection has emerged as a significant vulnerability in LLM-based systems. Learn effective strategies to protect your AI applications.",
    coverImage: "/blog/prompt-injection.jpg",
    category: "Technical",
    tags: ["LLM Security", "Prompt Engineering", "Cybersecurity"],
    author: {
      name: "John Doe",
      avatar: "/avatars/john-doe.jpg",
      role: "Security Engineer",
    },
    publishedAt: "2025-03-28",
    readTime: "12 min read",
    likes: 87,
    comments: 19,
  },
  {
    id: "healthcare-ai-compliance",
    title: "Navigating HIPAA Compliance with AI in Healthcare",
    excerpt:
      "Implementing AI in healthcare brings unique regulatory challenges. This guide helps you maintain HIPAA compliance while leveraging AI capabilities.",
    coverImage: "/blog/healthcare-ai.jpg",
    category: "Compliance",
    tags: ["Healthcare", "HIPAA", "Regulatory Compliance"],
    author: {
      name: "John Doe",
      avatar: "/avatars/john-doe.jpg",
      role: "Healthcare Solutions Director",
    },
    publishedAt: "2025-03-20",
    readTime: "10 min read",
    likes: 56,
    comments: 8,
  },
  {
    id: "financial-fraud-detection",
    title: "How AI is Revolutionizing Financial Fraud Detection",
    excerpt:
      "Financial institutions are leveraging AI to stay ahead of increasingly sophisticated fraud attempts. Discover the latest techniques and success stories.",
    coverImage: "/blog/financial-fraud.jpg",
    category: "Industry",
    tags: ["Finance", "Fraud Detection", "Case Study"],
    author: {
      name: "John Doe",
      avatar: "/avatars/john-doe.jpg",
      role: "FinTech Specialist",
    },
    publishedAt: "2025-03-19",
    readTime: "9 min read",
    likes: 93,
    comments: 15,
  },
  {
    id: "securing-home-iot",
    title: "Securing the Smart Home: Protecting IoT Devices with AI",
    excerpt:
      "As homes become smarter, they also become more vulnerable. Learn how AI-powered security can protect your connected devices and personal data.",
    coverImage: "/blog/smart-home.jpg",
    category: "Consumer",
    tags: ["IoT", "Smart Home", "Consumer Security"],
    author: {
      name: "John Doe",
      avatar: "/avatars/john-doe.jpg",
      role: "Product Manager",
    },
    publishedAt: "2025-03-18",
    readTime: "7 min read",
    likes: 112,
    comments: 27,
  },
  {
    id: "adversarial-machine-learning",
    title: "Understanding Adversarial Machine Learning Attacks",
    excerpt:
      "Adversarial attacks can manipulate AI systems in subtle but dangerous ways. This technical deep dive explains how they work and how to defend against them.",
    coverImage: "/blog/adversarial-ml.jpg",
    category: "Technical",
    tags: ["Adversarial ML", "Deep Learning", "Model Security"],
    author: {
      name: "John Doe",
      avatar: "/avatars/john-doe.jpg",
      role: "ML Security Researcher",
    },
    publishedAt: "2025-03-10",
    readTime: "15 min read",
    likes: 76,
    comments: 23,
  },
];
